source 'https://supermarket.chef.io'

cookbook 'apt', '~> 7.1.0'
cookbook 'git', '~> 9.0.1'
cookbook 'monit', '~> 1.0.0'
cookbook 'mysql', '~> 8.5.1'
cookbook 'ncdu', '~> 1.0.0'
cookbook 'nginx', '~> 8.1.5'
cookbook 'nodejs', '~> 5.0.0'
cookbook 'openssh', '~> 2.7.0'
cookbook 'swap_tuning', '~> 0.2.0'
cookbook 'sudo', '~> 5.4.2'
cookbook 'runit', '~> 3.0.5'
cookbook 'rvm', '~> 0.9.4'
cookbook 'ufw', '~> 3.2.0'
cookbook 'users', '~> 4.0.3'
